import type { FundingProgramInput } from "@/domain/programs";

export const seedPrograms: FundingProgramInput[] = [
  // ── Grants — EU-wide ───────────────────────────────────────────────
  {
    kind: "grant",
    provider: "European Innovation Council",
    program_name: "EIC Accelerator",
    url: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
    geography_scope: { scope: "EU" },
    sectors: [],
    domains: ["deeptech", "climate", "healthtech"],
    min_amount: "500000.00",
    max_amount: "2500000.00",
    typical_amount: "2500000.00",
    eligibility_rules: { trl_range: [5, 9], sme_required: true },
    source: "seed",
    confidence: "high",
  },
  {
    kind: "grant",
    provider: "European Innovation Council",
    program_name: "EIC Pathfinder",
    url: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-pathfinder_en",
    geography_scope: { scope: "EU" },
    sectors: [],
    domains: ["deeptech"],
    min_amount: "1000000.00",
    max_amount: "4000000.00",
    eligibility_rules: { trl_range: [1, 4], consortium_required: true },
    source: "seed",
    confidence: "high",
  },
  {
    kind: "grant",
    provider: "European Commission",
    program_name: "Horizon Europe — Pillar 2 Cluster 5 Climate",
    url: "https://ec.europa.eu/info/research-and-innovation/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en",
    geography_scope: { scope: "EU" },
    sectors: [],
    domains: ["climate", "energy"],
    min_amount: "2000000.00",
    max_amount: "10000000.00",
    eligibility_rules: { trl_range: [4, 7], consortium_required: true },
    source: "seed",
    confidence: "high",
  },
  {
    kind: "grant",
    provider: "EIT Climate-KIC",
    program_name: "Climate-KIC Accelerator",
    geography_scope: { scope: "EU" },
    sectors: [],
    domains: ["climate"],
    min_amount: "20000.00",
    max_amount: "100000.00",
    eligibility_rules: { trl_range: [3, 7], sme_required: true, age_max_years: 7 },
    source: "seed",
    confidence: "high",
  },

  // ── Grants — Austria ───────────────────────────────────────────────
  {
    kind: "grant",
    provider: "FFG",
    program_name: "Basisprogramm",
    url: "https://www.ffg.at/programm/basisprogramm",
    geography_scope: { scope: "national", countries: ["AT"] },
    sectors: [],
    domains: [],
    min_amount: "100000.00",
    max_amount: "3000000.00",
    eligibility_rules: { trl_range: [3, 8] },
    source: "seed",
    confidence: "high",
  },
  {
    kind: "grant",
    provider: "aws",
    program_name: "PreSeed | Seedfinancing — Innovative Solutions",
    url: "https://www.aws.at/aws-preseed-seedfinancing-innovative-solutions/",
    geography_scope: { scope: "national", countries: ["AT"] },
    sectors: [],
    domains: ["deeptech"],
    min_amount: "200000.00",
    max_amount: "800000.00",
    eligibility_rules: { sme_required: true, age_max_years: 5, legal_forms: ["GmbH", "AG"] },
    source: "seed",
    confidence: "high",
  },
  {
    kind: "grant",
    provider: "aws",
    program_name: "Innovation Voucher",
    geography_scope: { scope: "national", countries: ["AT"] },
    sectors: [],
    domains: [],
    min_amount: "5000.00",
    max_amount: "12500.00",
    eligibility_rules: { sme_required: true },
    source: "seed",
    confidence: "high",
  },

  // ── Grants — Germany ───────────────────────────────────────────────
  {
    kind: "grant",
    provider: "BMWK",
    program_name: "EXIST-Forschungstransfer",
    geography_scope: { scope: "national", countries: ["DE"] },
    sectors: [],
    domains: ["deeptech"],
    min_amount: "100000.00",
    max_amount: "300000.00",
    eligibility_rules: { trl_range: [3, 6] },
    source: "seed",
    confidence: "high",
  },
  {
    kind: "grant",
    provider: "BMBF",
    program_name: "KMU-innovativ",
    geography_scope: { scope: "national", countries: ["DE"] },
    sectors: [],
    domains: [],
    min_amount: "100000.00",
    max_amount: "2500000.00",
    eligibility_rules: { trl_range: [3, 7], sme_required: true },
    source: "seed",
    confidence: "high",
  },

  // ── Equity — EU/DACH-active ────────────────────────────────────────
  {
    kind: "equity",
    provider: "Speedinvest",
    program_name: "Pre-seed / Seed",
    url: "https://www.speedinvest.com/",
    geography_scope: { scope: "EU" },
    sectors: [],
    domains: ["fintech", "saas", "deeptech"],
    min_amount: "300000.00",
    max_amount: "3000000.00",
    typical_amount: "1500000.00",
    eligibility_rules: {},
    source: "seed",
    confidence: "high",
  },
  {
    kind: "equity",
    provider: "EIT InnoEnergy",
    program_name: "Highway Investment",
    geography_scope: { scope: "EU" },
    sectors: [],
    domains: ["energy", "climate"],
    min_amount: "200000.00",
    max_amount: "5000000.00",
    eligibility_rules: { age_max_years: 7 },
    source: "seed",
    confidence: "medium",
  },
  {
    kind: "equity",
    provider: "European Investment Fund",
    program_name: "InvestEU SME Window — Equity",
    geography_scope: { scope: "EU" },
    sectors: [],
    domains: [],
    min_amount: "500000.00",
    max_amount: "15000000.00",
    eligibility_rules: { sme_required: true },
    source: "seed",
    confidence: "high",
  },

  // ── Debt — EU/DACH ─────────────────────────────────────────────────
  {
    kind: "debt",
    provider: "European Investment Bank",
    program_name: "Venture Debt",
    geography_scope: { scope: "EU" },
    sectors: [],
    domains: [],
    min_amount: "5000000.00",
    max_amount: "50000000.00",
    eligibility_rules: { sme_required: false },
    source: "seed",
    confidence: "high",
  },
  {
    kind: "debt",
    provider: "aws",
    program_name: "ERP-Kredit",
    geography_scope: { scope: "national", countries: ["AT"] },
    sectors: [],
    domains: [],
    min_amount: "100000.00",
    max_amount: "30000000.00",
    eligibility_rules: { sme_required: true },
    source: "seed",
    confidence: "high",
  },

  // ── Alternative ────────────────────────────────────────────────────
  {
    kind: "alternative",
    provider: "Conda",
    program_name: "Crowdfinanzierung",
    geography_scope: { scope: "EU", countries: ["AT", "DE"] },
    sectors: [],
    domains: [],
    min_amount: "50000.00",
    max_amount: "5000000.00",
    eligibility_rules: { age_max_years: 10 },
    source: "seed",
    confidence: "medium",
  },
];
